/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.utp.interfaces;
import conexion.ConexionBD;
import static conexion.Metodos_sql.sql;
import java.awt.Color;
//import conexion.Metodos_sql;
//import interfaz.Inicio;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static edu.utp.interfaces.Clientes.id;
import java.awt.Toolkit;

/**
 *
 * @author Casa
 */
public class EditarCliente extends javax.swing.JFrame {
    ConexionBD conexion = new ConexionBD();
    Connection cn;
    Statement st;
    ResultSet rs;
    int id_num;
    /**
     * Creates new form EditarCliente
     */
    public EditarCliente() {
        initComponents();
        setLocationRelativeTo(null);
        listar();
        this.setBackground(new Color(0,0,0,0));
        jPanel1.setBackground(new Color(0,0,0,0));
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icons/logo.png")));
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_telefono = new javax.swing.JTextField();
        txt_type = new javax.swing.JTextField();
        txt_num = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        txt_departamento = new javax.swing.JTextField();
        txt_provincia = new javax.swing.JTextField();
        txt_distrito = new javax.swing.JTextField();
        txt_correo = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lbl_id2 = new javax.swing.JLabel();
        btn_exit = new javax.swing.JLabel();
        btn_guardar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_telefono.setBorder(null);
        jPanel1.add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 110, 30));

        txt_type.setBorder(null);
        jPanel1.add(txt_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 120, 30));

        txt_num.setBorder(null);
        jPanel1.add(txt_num, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 140, 30));

        txt_name.setBorder(null);
        jPanel1.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 180, 30));

        txt_departamento.setBorder(null);
        jPanel1.add(txt_departamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 140, 30));

        txt_provincia.setBorder(null);
        jPanel1.add(txt_provincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 150, 30));

        txt_distrito.setBorder(null);
        jPanel1.add(txt_distrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 160, 20));

        txt_correo.setBorder(null);
        jPanel1.add(txt_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 230, 20));

        txt_direccion.setBorder(null);
        jPanel1.add(txt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 460, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/NewEdit/Direccion.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));
        jPanel1.add(lbl_id2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 40, 20));

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/NewEdit/Boton-eliminar.png"))); // NOI18N
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitMouseClicked(evt);
            }
        });
        jPanel1.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, -1, 40));

        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/NewEdit/Boton-editar.png"))); // NOI18N
        btn_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_guardarMouseClicked(evt);
            }
        });
        jPanel1.add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, -1, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/NewEdit/Editar.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 490));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_exitMouseClicked

    private void btn_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guardarMouseClicked
        // TODO add your handling code here:
        //guarda la data en la DB
        guardar();
        this.dispose();
    }//GEN-LAST:event_btn_guardarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarCliente().setVisible(true);
            }
        });
    }
    
    void listar(){

        String sql="select * from clientes where id_cliente="+id;

        try{
            cn=conexion.conectar();
            st=cn.createStatement();
            rs=st.executeQuery(sql);
            Object[]clientes=new Object[11];
           
           
            while(rs.next()){
                clientes[0] = rs.getString("id_cliente");
                clientes[1] = rs.getString("nombre");
                clientes[2] = rs.getString("apellidos");
                clientes[3] = rs.getString("tipo_documento");
                clientes[4] = rs.getString("numero_documento");
                clientes[5] = rs.getString("direccion");
                clientes[6] = rs.getString("departamento");
                clientes[7] = rs.getString("provincia");
                clientes[8] = rs.getString("distrito");
                clientes[9] = rs.getString("telefono");
                clientes[10] = rs.getString("correo");
            }
            
            txt_name.setText(""+clientes[1]);
            txt_name.setText(""+clientes[2]);
            txt_type.setText(""+clientes[3]);
            txt_num.setText(""+clientes[4]);
            txt_direccion.setText(""+clientes[5]);
            txt_departamento.setText(""+clientes[6]);
            txt_provincia.setText(""+clientes[7]);
            txt_distrito.setText(""+clientes[8]);
            txt_telefono.setText(""+clientes[9]);
            txt_correo.setText(""+clientes[10]);
            
            
        }catch (SQLException e) {
            System.out.println("error : " + e.getMessage());
            System.out.println("esto viene de editar error id_cliente:" + id);
        }
    }
    
    void guardar(){

        String nombre=txt_name.getText();
        String tipo_documento=txt_type.getText();
        String numero_documento=txt_num.getText();
        String direccion=txt_direccion.getText();
        String depa=txt_departamento.getText();
        String prov=txt_provincia.getText();
        String distrito=txt_distrito.getText();
        String telef=txt_telefono.getText();
        String correo=txt_correo.getText();

        String sql="update clientes set nombre='"+nombre+"',tipo_documento='"+tipo_documento+"'"
                + ",numero_documento='"+numero_documento+"',direccion='"+direccion+"',departamento='"
                +depa+"',provincia='"+prov+"',distrito='"+distrito+"',telefono='"+telef+"',correo='"+correo+"' where id_cliente="+id;
        
        if(nombre.equals("")||tipo_documento.equals("")||numero_documento.equals("")){
            JOptionPane.showMessageDialog(null,"Ingrese los campos obligatorios");
        }else{
            try{
                cn=conexion.conectar();
                st=cn.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null,"Usuario Actualizado");
                }catch(Exception e){
                JOptionPane.showMessageDialog(null,"error al modificar :"+e.getMessage());
                }
        }
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel btn_exit;
    public static javax.swing.JLabel btn_guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel lbl_id2;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_departamento;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_distrito;
    private javax.swing.JTextField txt_name;
    public javax.swing.JTextField txt_num;
    private javax.swing.JTextField txt_provincia;
    public javax.swing.JTextField txt_telefono;
    public javax.swing.JTextField txt_type;
    // End of variables declaration//GEN-END:variables
}
