/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.utp.interfaces;

import conexion.ConexionBD;
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Objects;
import javax.swing.JComboBox;
import javax.swing.JFrame;

/**
 *
 * @author Casa
 */
public class NuevoCliente extends javax.swing.JFrame {

    ConexionBD conexion = new ConexionBD();
    Connection cn;
    Statement st;
    ResultSet rs;
    Clientes cliente = null;
    Comprobante comprobante = null;
    Cliente editar = null;

    public NuevoCliente(JFrame parent, Cliente editar) {
        if (parent instanceof Clientes) {
            this.cliente = (Clientes) parent;
        } else if (parent instanceof Comprobante) {
            this.comprobante = (Comprobante) parent;
        }

        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icons/logo.png")));

        if (Objects.nonNull(editar)) {
            this.editar = editar;
            this.combo_tipodoc.setSelectedItem(this.editar.getTipo_documento());
            this.txt_numero.setText(this.editar.getNumero_documento());
            this.txt_telefono.setText(this.editar.getTelefono());
            this.txt_nombre.setText(this.editar.getNombre());
            this.txt_apellidos.setText(this.editar.getApellidos());
            this.txt_departamento.setText(this.editar.getDepartamento());
            this.txt_provincia.setText(this.editar.getProvincia());
            this.txt_distrito.setText(this.editar.getDistrito());
            this.txt_email.setText(this.editar.getCorreo());
            this.txt_direccion.setText(this.editar.getDireccion());
        }
        setLocationRelativeTo(null);
        this.setBackground(new Color(0, 0, 0, 0));
        jPanel1.setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_guardar = new javax.swing.JLabel();
        btn_exit = new javax.swing.JLabel();
        txt_telefono = new javax.swing.JTextField();
        txt_numero = new javax.swing.JTextField();
        txt_provincia = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_apellidos = new javax.swing.JTextField();
        txt_departamento = new javax.swing.JTextField();
        txt_distrito = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        combo_tipodoc = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(760, 520));
        jPanel1.setPreferredSize(new java.awt.Dimension(760, 520));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/NewEdit/Boton-editar.png"))); // NOI18N
        btn_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_guardarMouseClicked(evt);
            }
        });
        jPanel1.add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 470, -1, -1));

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/NewEdit/Boton-eliminar.png"))); // NOI18N
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitMouseClicked(evt);
            }
        });
        jPanel1.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, -1, -1));

        txt_telefono.setBorder(null);
        txt_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telefonoActionPerformed(evt);
            }
        });
        txt_telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_telefonoKeyTyped(evt);
            }
        });
        jPanel1.add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 130, 20));

        txt_numero.setBorder(null);
        txt_numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_numeroActionPerformed(evt);
            }
        });
        txt_numero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_numeroKeyTyped(evt);
            }
        });
        jPanel1.add(txt_numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 130, 30));

        txt_provincia.setBorder(null);
        txt_provincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_provinciaActionPerformed(evt);
            }
        });
        txt_provincia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_provinciaKeyTyped(evt);
            }
        });
        jPanel1.add(txt_provincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 160, 30));

        txt_nombre.setBorder(null);
        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });
        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombreKeyTyped(evt);
            }
        });
        jPanel1.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 180, 30));

        txt_apellidos.setBorder(null);
        txt_apellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_apellidosActionPerformed(evt);
            }
        });
        txt_apellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_apellidosKeyTyped(evt);
            }
        });
        jPanel1.add(txt_apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 200, 20));

        txt_departamento.setBorder(null);
        txt_departamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_departamentoActionPerformed(evt);
            }
        });
        txt_departamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_departamentoKeyTyped(evt);
            }
        });
        jPanel1.add(txt_departamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 140, 30));

        txt_distrito.setBorder(null);
        txt_distrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_distritoActionPerformed(evt);
            }
        });
        txt_distrito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_distritoKeyTyped(evt);
            }
        });
        jPanel1.add(txt_distrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 160, 30));

        txt_email.setBorder(null);
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        jPanel1.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 200, 30));

        txt_direccion.setBorder(null);
        jPanel1.add(txt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 310, 30));

        combo_tipodoc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combo_tipodoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "RUC" }));
        jPanel1.add(combo_tipodoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 180, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/NewEdit/ocultar.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/NewEdit/Cliente.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefonoActionPerformed

    private void txt_numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_numeroActionPerformed

    private void txt_provinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_provinciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_provinciaActionPerformed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void txt_departamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_departamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_departamentoActionPerformed

    private void txt_distritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_distritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_distritoActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void btn_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guardarMouseClicked
        // TODO add your handling code here:

        if (Objects.nonNull(editar) && Objects.nonNull(editar.getId_cliente())) {
            editar_cliente();
        } else {
            crear_cliente();
        }
        this.dispose();
    }//GEN-LAST:event_btn_guardarMouseClicked

    private void btn_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_exitMouseClicked

    private void txt_apellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_apellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_apellidosActionPerformed

    private void txt_numeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_numeroKeyTyped
        // TODO add your handling code here:
        if(txt_numero.getText().length()>=11){
            evt.consume();
        }
        char validar=evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txt_numeroKeyTyped

    private void txt_telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telefonoKeyTyped
        // TODO add your handling code here:
        if(txt_telefono.getText().length()>=9){
            evt.consume();
        }
        char validar=evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txt_telefonoKeyTyped

    private void txt_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txt_nombreKeyTyped

    private void txt_apellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_apellidosKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txt_apellidosKeyTyped

    private void txt_departamentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_departamentoKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txt_departamentoKeyTyped

    private void txt_provinciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_provinciaKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txt_provinciaKeyTyped

    private void txt_distritoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_distritoKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txt_distritoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoCliente(null, null).setVisible(true);
            }
        });
    }

    void crear_cliente() {
        String nombre = txt_nombre.getText();
        String apellidos = txt_apellidos.getText();
        String tipo = combo_tipodoc.getSelectedItem().toString();
        String numero_doc = txt_numero.getText();
        String direc = txt_direccion.getText();
        String depa = txt_departamento.getText();
        String prov = txt_provincia.getText();
        String distrito = txt_distrito.getText();
        String telef = txt_telefono.getText();
        String correo = txt_email.getText();

        if (nombre.equals("") || tipo.equals("") || numero_doc.equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese los campos obligatorios");
            //limpiartabla();
        } else {
            String sql = "insert into clientes (nombre,apellidos,tipo_documento,numero_documento,direccion,departamento,provincia,distrito,telefono,correo)"
                    + "values('" + nombre + "','" + apellidos + "','" + tipo + "','" + numero_doc + "','" + direc + "','" + depa + "','" + prov + "','" + distrito + "','" + telef + "','" + correo + "')";

            System.err.println(sql);
            try {
                cn = conexion.conectar();
                st = cn.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Cliente Agregado");
                if (this.cliente != null) {
                    this.cliente.listar("");
                } else if (this.comprobante != null) {
                    this.comprobante.mostrarcliente();
                }
            } catch (Exception e) {
                System.out.println("Error" + e.getMessage());
            }
        }
    }

    void editar_cliente() {
        String nombre = txt_nombre.getText();
        String apellidos = txt_apellidos.getText();
        String tipo_documento = combo_tipodoc.getSelectedItem().toString();
        String numero_documento = txt_numero.getText();
        String direccion = txt_direccion.getText();
        String depa = txt_departamento.getText();
        String prov = txt_provincia.getText();
        String distrito = txt_distrito.getText();
        String telef = txt_telefono.getText();
        String correo = txt_email.getText();

        String sql = "update clientes set nombre='" + nombre + "',apellidos='" + apellidos + "',tipo_documento='" + tipo_documento
                + "',numero_documento='" + numero_documento + "',direccion='" + direccion + "',departamento='"
                + depa + "',provincia='" + prov + "',distrito='" + distrito + "',telefono='" + telef + "',correo='" + correo + "' where id_cliente=" + this.editar.getId_cliente();

        System.out.println(sql);
        if (nombre.equals("") || tipo_documento.equals("") || numero_documento.equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese los campos obligatorios");
        } else {
            try {
                cn = conexion.conectar();
                st = cn.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Cliente Actualizado");
                if (this.cliente != null) {
                    this.cliente.listar("");
                } else if (this.comprobante != null) {
                    this.comprobante.mostrarcliente();
                }
            } catch (Exception e) {
                System.out.println(sql);
                JOptionPane.showMessageDialog(null, "error al modificar :" + e.getMessage());
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_exit;
    private javax.swing.JLabel btn_guardar;
    private javax.swing.JComboBox<String> combo_tipodoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_apellidos;
    private javax.swing.JTextField txt_departamento;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_distrito;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_numero;
    private javax.swing.JTextField txt_provincia;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
