/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.pkg2;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import conexion.ConexionBD;
import javax.swing.JOptionPane;
import static project.pkg2.AdminUsuarios.id;
/**
 *
 * @author Casa
 */
public class EditarUsuario extends javax.swing.JFrame {
    ConexionBD conexion = new ConexionBD();
    Connection cn;
    Statement st;
    ResultSet rs;
    int id_num;
    /**
     * Creates new form EditarUsuario
     */
    public EditarUsuario() {
        initComponents();
        setLocationRelativeTo(null);
        listar();
        this.setBackground(new Color(0,0,0,0));
        jPanel1.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_Nombre = new javax.swing.JTextField();
        txt_Apellido = new javax.swing.JTextField();
        txt_Correo = new javax.swing.JTextField();
        txt_Permisos = new javax.swing.JTextField();
        btn_cancelar = new javax.swing.JLabel();
        btn_guardar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_Nombre.setBorder(null);
        jPanel1.add(txt_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 220, 20));

        txt_Apellido.setBorder(null);
        jPanel1.add(txt_Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 220, 20));

        txt_Correo.setBorder(null);
        jPanel1.add(txt_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 220, 20));

        txt_Permisos.setBorder(null);
        jPanel1.add(txt_Permisos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 100, 20));

        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Usuarios/Boton_cancelar.png"))); // NOI18N
        btn_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cancelarMouseClicked(evt);
            }
        });
        jPanel1.add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, -1, -1));

        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Usuarios/Boton_guardar.png"))); // NOI18N
        btn_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_guardarMouseClicked(evt);
            }
        });
        jPanel1.add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Usuarios/EditarUsuario.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 430));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelarMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_cancelarMouseClicked

    private void btn_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guardarMouseClicked
        // TODO add your handling code here:
        guardar();
        this.dispose();
    }//GEN-LAST:event_btn_guardarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarUsuario().setVisible(true);
            }
        });
    }
    void listar(){

        String sql="select * from usuarios where id_usuario="+id;

        try{
            cn=conexion.conectar();
            st=cn.createStatement();
            rs=st.executeQuery(sql);
            Object[]clientes=new Object[5];
           
           
            while(rs.next()){
            clientes[0]=rs.getString("id_usuario");    
            clientes[1]=rs.getString("nombre");
            clientes[2]=rs.getString("apellidos");
            clientes[3]=rs.getString("correo");
            clientes[4]=rs.getString("permisos");

            }
            
            txt_Nombre.setText(""+clientes[1]);
            txt_Apellido.setText(""+clientes[2]);
            txt_Correo.setText(""+clientes[3]);
            txt_Permisos.setText(""+clientes[4]);

            
            
        }catch (SQLException e){
             System.out.println("error : "+e.getMessage());
            System.out.println("esto viene de editar error id_usuario:"+id);
        }
    }
    void guardar(){

        String nombre=txt_Nombre.getText();
        String apellido=txt_Apellido.getText();
        String correo=txt_Correo.getText();
        String permiso=txt_Permisos.getText();

        String sql="update usuarios set nombre='"+nombre+"',apellidos='"+apellido+"'"
                + ",correo='"+correo+"',permisos='"+permiso+"' where id_usuario="+id;
        
        if(nombre.equals("")||apellido.equals("")||correo.equals("")){
            JOptionPane.showMessageDialog(null,"Ingrese los campos obligatorios");
        }else{
            try{
                cn=conexion.conectar();
                st=cn.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null,"Usuario Actualizado");
                }catch(Exception e){
                JOptionPane.showMessageDialog(null,"error al modificar :"+e.getMessage());
                }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_cancelar;
    private javax.swing.JLabel btn_guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_Apellido;
    private javax.swing.JTextField txt_Correo;
    private javax.swing.JTextField txt_Nombre;
    private javax.swing.JTextField txt_Permisos;
    // End of variables declaration//GEN-END:variables
}
