/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.pkg2;

import conexion.ConexionBD;
import static conexion.Metodos_sql.conexion;
import java.awt.Color;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
/**
 *
 * @author Casa
 */
public class NuevoCliente extends javax.swing.JFrame {

    ConexionBD conexion = new ConexionBD();
    Connection cn;
    Statement st;
    ResultSet rs;
    /**
     * Creates new form NuevoCliente
     */
    public NuevoCliente() {
        initComponents();
        setLocationRelativeTo(null);
        this.setBackground(new Color(0,0,0,0));
        jPanel1.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_guardar = new javax.swing.JLabel();
        btn_exit = new javax.swing.JLabel();
        txt_telefono = new javax.swing.JTextField();
        txt_tipo = new javax.swing.JTextField();
        txt_numero = new javax.swing.JTextField();
        txt_provincia = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_departamento = new javax.swing.JTextField();
        txt_distrito = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/NewEdit/Boton-editar.png"))); // NOI18N
        btn_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_guardarMouseClicked(evt);
            }
        });
        jPanel1.add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 430, -1, -1));

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/NewEdit/Boton-eliminar.png"))); // NOI18N
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitMouseClicked(evt);
            }
        });
        jPanel1.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, -1, -1));

        txt_telefono.setBorder(null);
        txt_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telefonoActionPerformed(evt);
            }
        });
        jPanel1.add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 100, 30));

        txt_tipo.setBorder(null);
        txt_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tipoActionPerformed(evt);
            }
        });
        jPanel1.add(txt_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 120, 30));

        txt_numero.setBorder(null);
        txt_numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_numeroActionPerformed(evt);
            }
        });
        jPanel1.add(txt_numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 120, 30));

        txt_provincia.setBorder(null);
        txt_provincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_provinciaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_provincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 160, 30));

        txt_nombre.setBorder(null);
        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });
        jPanel1.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 180, 30));

        txt_departamento.setBorder(null);
        txt_departamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_departamentoActionPerformed(evt);
            }
        });
        jPanel1.add(txt_departamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 130, 30));

        txt_distrito.setBorder(null);
        txt_distrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_distritoActionPerformed(evt);
            }
        });
        jPanel1.add(txt_distrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 180, 20));

        txt_email.setBorder(null);
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        jPanel1.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 230, 20));

        txt_direccion.setBorder(null);
        jPanel1.add(txt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 460, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/NewEdit/Direccion.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 490, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/NewEdit/NuevoCliente.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 490));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefonoActionPerformed

    private void txt_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tipoActionPerformed

    private void txt_numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_numeroActionPerformed

    private void txt_provinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_provinciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_provinciaActionPerformed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void txt_departamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_departamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_departamentoActionPerformed

    private void txt_distritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_distritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_distritoActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void btn_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guardarMouseClicked
        // TODO add your handling code here:
        Agregar();
        this.dispose();
    }//GEN-LAST:event_btn_guardarMouseClicked

    private void btn_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_exitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoCliente().setVisible(true);
            }
        });
    }

    void Agregar(){
        String nombre=txt_nombre.getText();
        String tipo=txt_tipo.getText();
        String numero_doc=txt_numero.getText();
        String direc=txt_direccion.getText();
        String depa=txt_departamento.getText();
        String prov=txt_provincia.getText();
        String distrito=txt_distrito.getText();
        String telef=txt_telefono.getText();
        String correo=txt_email.getText();
        
        if(nombre.equals("")||tipo.equals("")||numero_doc.equals("")){
            JOptionPane.showMessageDialog(null,"Ingrese los campos obligatorios");
            //limpiartabla();
            }else{
            String sql="insert into clientes (nombre,tipo_documento,numero_documento,direccion,departamento,provincia,distrito,telefono,correo)"
                    + "values('"+nombre+"','"+tipo+"','"+numero_doc+"','"+direc+"','"+depa+"','"+prov+"','"+distrito+"','"+telef+"','"+correo+"')";
                try{
                cn=conexion.conectar();
                st=cn.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null,"Usuario Agregado");
                
                
                }catch(Exception e){
                    System.out.println("Error"+e.getMessage());
                }
        }
    }
    
    
   /* void Limpiar(){
        
        txt_nombre.setText("");
        txt_tipo.setText("");
        txt_numero.setText("");
        txt_departamento.setText("");
        txt_provincia.setText("");
        txt_distrito.setText("");
        txt_telefono.setText("");
        txt_email.setText("");
       
    }*/
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_exit;
    private javax.swing.JLabel btn_guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_departamento;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_distrito;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_numero;
    private javax.swing.JTextField txt_provincia;
    private javax.swing.JTextField txt_telefono;
    private javax.swing.JTextField txt_tipo;
    // End of variables declaration//GEN-END:variables
}
