/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.pkg2;
import conexion.ConexionBD;
import static conexion.Metodos_sql.conexion;
import java.awt.Color;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Casa
 */
public class NuevoProducto extends javax.swing.JFrame {
    ConexionBD conexion = new ConexionBD();
    Connection cn;
    Statement st;
    ResultSet rs;
    /**
     * Creates new form NuevoProducto
     */
    public NuevoProducto() {
        initComponents();
        setLocationRelativeTo(null);
        this.setBackground(new Color(0,0,0,0));
        jPanel1.setBackground(new Color(0,0,0,0));
        mostrarcategoria();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_codigo = new javax.swing.JTextField();
        txt_descripcion = new javax.swing.JTextField();
        txt_preciocompra = new javax.swing.JTextField();
        txt_stock = new javax.swing.JTextField();
        txt_precioventa = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        combo_categoria = new javax.swing.JComboBox<>();
        btn_cancelar = new javax.swing.JLabel();
        btn_agregar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_codigo.setBorder(null);
        jPanel1.add(txt_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 120, 30));

        txt_descripcion.setBorder(null);
        jPanel1.add(txt_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 580, 60));

        txt_preciocompra.setBorder(null);
        jPanel1.add(txt_preciocompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 120, 30));

        txt_stock.setBorder(null);
        jPanel1.add(txt_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 120, 30));

        txt_precioventa.setBorder(null);
        jPanel1.add(txt_precioventa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 120, 30));

        txt_nombre.setBorder(null);
        jPanel1.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 370, 30));

        combo_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una categoria" }));
        combo_categoria.setBorder(null);
        jPanel1.add(combo_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 250, 30));

        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/NewEdit/Boton-eliminar.png"))); // NOI18N
        btn_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cancelarMouseClicked(evt);
            }
        });
        jPanel1.add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, -1, -1));

        btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/NewEdit/Boton-editar.png"))); // NOI18N
        btn_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregarMouseClicked(evt);
            }
        });
        jPanel1.add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 440, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/productos/NuevoProducto.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarMouseClicked
        // TODO add your handling code here:
        Agregar();
        this.dispose();
    }//GEN-LAST:event_btn_agregarMouseClicked

    private void btn_cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelarMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_cancelarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoProducto().setVisible(true);
            }
        });
    }

        void Agregar(){
        
        String codigo=txt_codigo.getText();
        String nombre=txt_nombre.getText();
        String descripcion=txt_descripcion.getText();
        String preciocompra=txt_preciocompra.getText();
        String precioventa=txt_precioventa.getText();
        String stock=txt_stock.getText();
        Integer id_categoria=combo_categoria.getSelectedIndex();
        
        if(codigo.equals("")||nombre.equals("")||stock.equals("")){
            JOptionPane.showMessageDialog(null,"Ingrese los campos obligatorios");
            //limpiartabla();
            }else{
            String sql="insert into productos (id_categoria,codigo,nombre,precio_venta,stock,descripcion,precio_compra)"
                    + "values('"+id_categoria+"','"+codigo+"','"+nombre+"','"+precioventa+"','"+stock+"','"+descripcion+"','"+preciocompra+"')";
                try{
                cn=conexion.conectar();
                st=cn.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null,"Producto Agregado");
                //Clientes cl = new Clientes ();
                //cl.actualizar.doClick();
                
                }catch(HeadlessException | SQLException e){
                    System.out.println("Error");
                }
        }
    }
        
    //para el combobox
    void mostrarcategoria(){
        String sql="Select * from categoria";
        cn=conexion.conectar();
    try {

        st=cn.createStatement();
        ResultSet rs=st.executeQuery(sql);
        while(rs.next()){
        combo_categoria.addItem(rs.getString("nombre")); //nombre de la cabecera tabla pa mostrar
        }

    } catch (SQLException ex) {
        Logger.getLogger(NuevoProducto.class.getName()).log(Level.SEVERE, null, ex);
    }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_agregar;
    private javax.swing.JLabel btn_cancelar;
    public static javax.swing.JComboBox<String> combo_categoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_descripcion;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_preciocompra;
    private javax.swing.JTextField txt_precioventa;
    private javax.swing.JTextField txt_stock;
    // End of variables declaration//GEN-END:variables
}
