/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.pkg2;
import conexion.ConexionBD;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
//import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Casa
 */
public class Productos extends javax.swing.JFrame {
    
    ConexionBD conexion = new ConexionBD();
    Connection cn;
    Statement st;
    ResultSet rs;
    DefaultTableModel modeloP;
    static int idP;
    Integer idUsuario ;
    /**
     * Creates new form Productos
     */
    public Productos(Integer idUsuario) {
        this.idUsuario = idUsuario;
        initComponents();
        setLocationRelativeTo(null);
        this.setBackground(new Color(0,0,0,0));
        jPanel1.setBackground(new Color(0,0,0,0));
        listarP(txt_buscarP.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_comprobante = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_clientes = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_guardarP = new javax.swing.JLabel();
        btn_editar = new javax.swing.JLabel();
        btn_eliminar = new javax.swing.JLabel();
        txt_buscarP = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lbl_idP = new javax.swing.JLabel();
        lbl_cod = new javax.swing.JLabel();
        lbl_precioventa = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        lbl_stock = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDatosP = new javax.swing.JTable();
        btn_actualizar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_comprobante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/clientes/Menu1.png"))); // NOI18N
        btn_comprobante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_comprobanteMouseClicked(evt);
            }
        });
        jPanel1.add(btn_comprobante, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/clientes/Menu2.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        btn_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/productos/Menu-Clientes.png"))); // NOI18N
        btn_clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_clientesMouseClicked(evt);
            }
        });
        jPanel1.add(btn_clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/productos/Menu-productos.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        btn_guardarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/NewEdit/Boton-agregar.png"))); // NOI18N
        btn_guardarP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_guardarPMouseClicked(evt);
            }
        });
        jPanel1.add(btn_guardarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 70, -1, -1));

        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/clientes/Boton-editar.png"))); // NOI18N
        btn_editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_editarMouseClicked(evt);
            }
        });
        jPanel1.add(btn_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 160, -1, -1));

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/clientes/Boton-eliminar.png"))); // NOI18N
        btn_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarMouseClicked(evt);
            }
        });
        jPanel1.add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 160, -1, -1));

        txt_buscarP.setBorder(null);
        txt_buscarP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_buscarPKeyReleased(evt);
            }
        });
        jPanel1.add(txt_buscarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 590, 220, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/NewEdit/Boton-buscar.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 580, 330, 50));

        lbl_idP.setText("id");
        jPanel1.add(lbl_idP, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 20, -1));

        lbl_cod.setText("Cód. Interno");
        jPanel1.add(lbl_cod, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, -1, -1));

        lbl_precioventa.setText("P.Unitario");
        jPanel1.add(lbl_precioventa, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 170, -1, -1));

        lbl_nombre.setText("Nombre");
        jPanel1.add(lbl_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, -1, -1));

        lbl_stock.setText("Stock");
        jPanel1.add(lbl_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, -1, -1));

        TablaDatosP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód. Interno", "Nombre", "Stock", "P. Unitario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaDatosP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDatosPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaDatosP);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 690, 360));

        btn_actualizar.setText("Actualizar");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 600, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/productos/panel-right.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, 680));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/clientes/Panel-left.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 680));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablaDatosPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDatosPMouseClicked
        // TODO add your handling code here:
        int fila=TablaDatosP.getSelectedRow();
        if(fila==-1){
        JOptionPane.showMessageDialog(null,"Ingrese los campos obligatorios");
        }else{
        idP=Integer.parseInt((String)TablaDatosP.getValueAt(fila,0).toString());
        String codigo=(String)TablaDatosP.getValueAt(fila,1);
        String nombre=(String)TablaDatosP.getValueAt(fila,2);
        String stock=(String)TablaDatosP.getValueAt(fila,3);
        String precio_venta=(String)TablaDatosP.getValueAt(fila,4);
        

        lbl_idP.setText(""+idP);
        lbl_cod.setText(""+codigo);
        lbl_nombre.setText(""+nombre);
        lbl_stock.setText(""+stock);
        lbl_precioventa.setText(""+precio_venta);
        } 
    }//GEN-LAST:event_TablaDatosPMouseClicked

    private void btn_guardarPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guardarPMouseClicked
        // TODO add your handling code here:
        NuevoProducto nuevo = new NuevoProducto();
        
        nuevo.setVisible(true);
    }//GEN-LAST:event_btn_guardarPMouseClicked

    private void btn_editarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editarMouseClicked
        // TODO add your handling code here:
        EditarProducto edit = new EditarProducto();
        
        edit.setVisible(true);
    }//GEN-LAST:event_btn_editarMouseClicked

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        // TODO add your handling code here:
        listarP(txt_buscarP.getText());
    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void txt_buscarPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarPKeyReleased
        // TODO add your handling code here:
        listarP(txt_buscarP.getText());
    }//GEN-LAST:event_txt_buscarPKeyReleased

    private void btn_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarMouseClicked
        // TODO add your handling code here:
        eliminar();
        listarP(txt_buscarP.getText());
    }//GEN-LAST:event_btn_eliminarMouseClicked

    private void btn_clientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clientesMouseClicked
        // TODO add your handling code here:
        Clientes clientes = new Clientes(this.idUsuario);
        clientes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_clientesMouseClicked

    private void btn_comprobanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_comprobanteMouseClicked
        // TODO add your handling code here:
        Comprobante comp = new Comprobante(null);
        comp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_comprobanteMouseClicked
    
    void listarP(String nombre)  { //buscar()
    
        DefaultTableModel modeloP=new DefaultTableModel();
        modeloP.addColumn("id");
        modeloP.addColumn("codigo_interno");
        modeloP.addColumn("nombre");
        modeloP.addColumn("stock");
        modeloP.addColumn("precio_venta");
        modeloP.addColumn("categoria");
        

        TablaDatosP.setModel(modeloP);
        String sql="";
            if(nombre.equals("")){
                sql="Select P.id, P.codigo, P.nombre, P.stock, P.precio_venta, C.nombre from productos P JOIN categoria C ON P.id_categoria=C.id_categoria";
                
                
            }   else{
                //esto es para que busque letra por letra
                sql="Select P.id, P.codigo, P.nombre, P.stock, P.precio_venta, C.nombre from productos P "
                        + "JOIN categoria C ON P.id_categoria=C.id_categoria where p.nombre like'%"+nombre+"%'";
                }
            
      String Productos[]=new String[6];
      cn=conexion.conectar();

        try {
            st=cn.createStatement();
            ResultSet resul=st.executeQuery(sql);
            //mandamos datos al jtable
            while(resul.next()){
              Productos[0]=resul.getString(1);
              Productos[1]=resul.getString(2);
              Productos[2]=resul.getString(3);
              Productos[3]=resul.getString(4);
              Productos[4]=resul.getString(5);
              Productos[5]=resul.getString(6);


              modeloP.addRow(Productos);
            } 
        TablaDatosP.setModel(modeloP); 

        }catch (SQLException ex) {
            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    //esto es para que al listar no se dupliquen las entradas borra las anteriores :v
   void limpiartabla(){
        for(int i=0;i<=TablaDatosP.getRowCount()-1;i++){
        modeloP.removeRow(i);
       i=i-1;
        }
   }
    void eliminar(){
       int filaselccionado=TablaDatosP.getSelectedRow();
       if(filaselccionado==-1){
        JOptionPane.showMessageDialog(null,"Seleccione una fila para eliminar");
        }else{
           String sql="delete from productos where id="+idP;
            try{
                cn=conexion.conectar();
                st=cn.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null,"El producto fue eliminado");
                limpiartabla();
                
                }catch(Exception e){
                   System.out.println("error al eliminar");
                }
       }
   }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable TablaDatosP;
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JLabel btn_clientes;
    private javax.swing.JLabel btn_comprobante;
    private javax.swing.JLabel btn_editar;
    private javax.swing.JLabel btn_eliminar;
    private javax.swing.JLabel btn_guardarP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_cod;
    private javax.swing.JLabel lbl_idP;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_precioventa;
    private javax.swing.JLabel lbl_stock;
    public static javax.swing.JTextField txt_buscarP;
    // End of variables declaration//GEN-END:variables
}
